name: generate pacman game

on:
  schedule:
    - cron: "0 */24 * * *"     # Runs once daily
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        #with
        with:
          github_user_name: ${{ github.repository_owner }}
          theme: github-dark 

      - name: push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



#in yml file comment are use with "#"
#with:
  #github_user_name: ${{ github.repository_owner }}
  #platform: github              # 'github' or 'gitlab'
  #output_format: svg            # 'svg' or 'canvas'
  #theme: github-dark            # themes: 'github', 'github-dark', 'gitlab', 'gitlab-dark'
 # speed: 1                     # game speed, e.g., 1 (normal), 2 (fast)
  #sound: false                 # enable or disable sounds
  #player_style: aggressive     # 'conservative', 'aggressive', 'opportunistic'

